# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUyRI494JTtTDH64xX5sWhmLsHiGJQmk
"""

# Variável global
LIMITE_SEGURANCA = 10000

# Função
def analisar_vendas(venda1, venda2, venda3):
    global LIMITE_SEGURANCA

    # Média
    media = (venda1 + venda2 + venda3) / 3

    print("\n--- RESULTADO ---")
    print(f"Média: {media:.2f} | tipo: {type(media).__name__}")
    print(f"Limite: {LIMITE_SEGURANCA} | tipo: {type(LIMITE_SEGURANCA).__name__}")

    # REGRA 1: média acima do limite
    if media > LIMITE_SEGURANCA:
        print("SISTEMA EM QUARENTENA")

        resposta = input("Deseja atualizar o limite? (s/n): ")

        if resposta.lower() in ("s", "sim"):
            LIMITE_SEGURANCA = float(input("Novo limite: "))
            print("Limite atualizado!")

    # REGRA 2: discrepância
    encontrou = False

    if venda1 >= 5 * media:
        print("REVISÃO MANUAL: Venda 1 suspeita")
        encontrou = True

    if venda2 >= 5 * media:
        print("REVISÃO MANUAL: Venda 2 suspeita")
        encontrou = True

    if venda3 >= 5 * media:
        print("REVISÃO MANUAL: Venda 3 suspeita")
        encontrou = True

    vendas = sorted([venda1, venda2, venda3])
    mediana = vendas[1]

    if venda1 >= 3 * mediana or venda1 <= mediana / 3:
        print("REVISÃO MANUAL: Venda 1 suspeita")

    if venda2 >= 3 * mediana or venda2 <= mediana / 3:
        print("REVISÃO MANUAL: Venda 2 suspeita")

    if venda3 >= 3 * mediana or venda3 <= mediana / 3:
        print("REVISÃO MANUAL: Venda 3 suspeita")

    if not encontrou:
        print("Nenhuma discrepância detectada.")


# Entrada de dados
venda1 = float(input("Venda 1: R$"))
venda2 = float(input("Venda 2: R$"))
venda3 = float(input("Venda 3: R$"))

# Mostrando os tipos
print(f"\nVenda 1: R${venda1} | tipo: {type(venda1).__name__}")
print(f"Venda 2: R${venda2} | tipo: {type(venda2).__name__}")
print(f"Venda 3: R${venda3} | tipo: {type(venda3).__name__}")

# Chamada da função
analisar_vendas(venda1, venda2, venda3)